/**
 * src/capability/skill-index.ts — M4 external-skill index RUNTIME LOADER.
 *
 * Loads data/skill-index.json (generated by `npm run refresh-index`) MODULE-RELATIVE
 * (`../../data/skill-index.json` from dist/capability/ — never cwd-relative), validates
 * its shape, and returns a typed SkillIndex or null.
 *
 * FAIL-SILENT CONTRACT (the M4 hard constraint): this NEVER throws. A missing, stale,
 * or malformed index returns null and the feature is silently absent — the judge input
 * stays byte-identical to a build without the index. `isFresh` gates the HOT PATH only
 * (judge ride-along); `/coach find` works on any loadable index regardless of age.
 */

/** One external skill/plugin entry as written by scripts/refresh-skill-index.mjs. */
export interface SkillIndexEntry {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
  readonly description: string;
  readonly keywords: readonly string[];
  readonly category: string | null;
  /** The printed install command (e.g. `/plugin install pdf@anthropic-agent-skills`). NEVER executed. */
  readonly install: string;
  readonly sourceUrl: string;
  readonly trust: string;
  readonly pinnedSha: string | null;
  readonly repoStars: number | null;
}

export interface SkillIndex {
  readonly schemaVersion: 1;
  readonly generatedAt: string;
  readonly sources: readonly unknown[];
  readonly entries: readonly SkillIndexEntry[];
}

/** The slice of an entry that rides the judge prompt / the composed tip. G-M4b: carries
 *  `trust` so every renderer can label non-official entries as community/unverified. */
export type ExternalCandidate = Pick<
  SkillIndexEntry,
  'name' | 'description' | 'install' | 'sourceUrl' | 'trust'
> & { readonly repoStars: number | null };

/** Hot-path freshness gate: an index older than this never rides the judge prompt. */
export const MAX_INDEX_AGE_MS = 180 * 24 * 60 * 60 * 1000;

/**
 * Hardening cap on the two fields that ride composed tips VERBATIM (install command +
 * source URL). Applied at load-validation so no downstream renderer can be length-bombed.
 */
export const MAX_PRINTED_FIELD_CHARS = 200;

// ANSI CSI escape sequences (colors, cursor, erase) — stripped WHOLE so the printable
// payload ('[31m') never survives its ESC. Then any remaining C0/DEL control-char run
// collapses to a single space (scraped text must never carry terminal control bytes).
// eslint-disable-next-line no-control-regex
const ANSI_CSI_RE = /\x1b\[[0-9;:?]*[ -/]*[@-~]/g;
// eslint-disable-next-line no-control-regex
const CTRL_RE = /[\x00-\x1f\x7f-\x9f\u2028\u2029]+/g;

/**
 * Defense-in-depth sanitizer for any external-index string that gets printed or rides
 * an LLM prompt: strips ANSI escape sequences and control chars to a single space.
 * Pure; never throws. Shared by the loader, renderExternalSection, and `/coach find`.
 */
export function sanitizeExternalText(text: string): string {
  return text.replace(ANSI_CSI_RE, ' ').replace(CTRL_RE, ' ').replace(/ {2,}/g, ' ').trim();
}

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { isCleanCommunityText, NAME_RE } from './community-gate.js';

/** Module-relative default read — works from dist/capability/ AND src/capability/. */
function defaultRead(): string {
  return readFileSync(new URL('../../data/skill-index.json', import.meta.url), 'utf8');
}

// ── G-M4b: community load-side strictness pins ───────────────────────────────
/** The ONLY install-command shape a non-official entry may carry. */
export const INSTALL_RE = /^\/plugin install [a-z0-9][a-z0-9._-]*@[a-z0-9-]+$/;
/** Non-official sourceUrls must live on github.com. */
export const COMMUNITY_URL_PREFIX = 'https://github.com/';
/** Community descriptions are capped tighter than official ones (350 vs 400). */
const COMMUNITY_DESC_MAX_CHARS = 350;

const foldName = (s: string): string => s.trim().toLowerCase();
const alnumName = (s: string): string => foldName(s).replace(/[^a-z0-9]/g, '');

/**
 * G-M4b load-side strictness for a NON-official entry (defense-in-depth vs a poisoned
 * index file — the scrape-side gate already enforces this, but the loader must not
 * trust the file). Failure DROPS the entry, never the index: a poisoned community
 * entry must never deny the official index.
 */
function communityEntryOk(entry: SkillIndexEntry, rawDescription: unknown): boolean {
  if (!NAME_RE.test(entry.name)) return false;
  if (!INSTALL_RE.test(entry.install)) return false;
  if (!entry.sourceUrl.startsWith(COMMUNITY_URL_PREFIX)) return false;
  if (entry.description.length > COMMUNITY_DESC_MAX_CHARS) return false;
  // The RAW description must pass the injection lint (control bytes / ANSI / injection
  // phrases / non-github URLs present at all → reject, never sanitize-and-accept).
  if (typeof rawDescription !== 'string' || !isCleanCommunityText(rawDescription)) return false;
  return true;
}

/**
 * Load + validate the skill index. NEVER throws: any read/parse/shape failure → null
 * (feature silently absent, byte-identical judge input).
 */
export function loadSkillIndex(read: () => string = defaultRead): SkillIndex | null {
  try {
    const raw: unknown = JSON.parse(read());
    if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) return null;
    const obj = raw as Record<string, unknown>;
    if (obj.schemaVersion !== 1) return null;
    if (typeof obj.generatedAt !== 'string') return null;
    if (!Array.isArray(obj.entries)) return null;

    const entries: SkillIndexEntry[] = [];
    for (const item of obj.entries) {
      const entry = validateEntry(item);
      if (entry === null) return null; // one malformed entry rejects the whole index.
      // G-M4b: a NON-official entry additionally passes the community strictness or is
      // DROPPED (entry-level — a poisoned community entry never denies the official index).
      if (entry.trust !== 'official') {
        const rawDescription = (item as Record<string, unknown>).description;
        if (!communityEntryOk(entry, rawDescription)) continue;
      }
      entries.push(entry);
    }

    // G-M4b: drop community entries that shadow an official name in the SAME index
    // (fold AND alnum-lookalike — 'skillcreator' cannot shadow 'skill-creator').
    const officialFolds = new Set<string>();
    const officialAlnums = new Set<string>();
    for (const e of entries) {
      if (e.trust === 'official') {
        officialFolds.add(foldName(e.name));
        officialAlnums.add(alnumName(e.name));
      }
    }
    const deduped = entries.filter(
      (e) =>
        e.trust === 'official' ||
        (!officialFolds.has(foldName(e.name)) && !officialAlnums.has(alnumName(e.name))),
    );

    return {
      schemaVersion: 1,
      generatedAt: obj.generatedAt,
      sources: Array.isArray(obj.sources) ? obj.sources : [],
      entries: deduped,
    };
  } catch {
    return null;
  }
}

/**
 * Validate one entry: the four required strings are hard; the rest get safe defaults.
 * Hardening: every printed string is sanitized (control chars / ANSI stripped) at load,
 * and install/sourceUrl are capped at MAX_PRINTED_FIELD_CHARS so composed tips can never
 * be length-bombed. A required field that sanitizes to empty rejects the entry.
 */
function validateEntry(item: unknown): SkillIndexEntry | null {
  if (item === null || typeof item !== 'object' || Array.isArray(item)) return null;
  const e = item as Record<string, unknown>;
  for (const field of ['name', 'description', 'install', 'sourceUrl'] as const) {
    if (typeof e[field] !== 'string' || (e[field] as string).length === 0) return null;
  }
  const name = sanitizeExternalText(e.name as string);
  const description = sanitizeExternalText(e.description as string);
  const install = sanitizeExternalText(e.install as string).slice(0, MAX_PRINTED_FIELD_CHARS);
  const sourceUrl = sanitizeExternalText(e.sourceUrl as string).slice(0, MAX_PRINTED_FIELD_CHARS);
  if ([name, description, install, sourceUrl].some((v) => v.length === 0)) return null;
  return {
    id: typeof e.id === 'string' ? e.id : name,
    name,
    kind: typeof e.kind === 'string' ? e.kind : 'skill',
    description,
    keywords: Array.isArray(e.keywords)
      ? e.keywords.filter((k): k is string => typeof k === 'string')
      : [],
    category: typeof e.category === 'string' ? e.category : null,
    install,
    sourceUrl,
    trust: typeof e.trust === 'string' ? e.trust : 'unknown',
    pinnedSha: typeof e.pinnedSha === 'string' ? e.pinnedSha : null,
    repoStars: typeof e.repoStars === 'number' ? e.repoStars : null,
  };
}

/**
 * Hot-path freshness: true iff generatedAt parses AND is within MAX_INDEX_AGE_MS of
 * nowMs. An unparseable date is STALE (fail-closed — the ride-along stays absent).
 */
export function isFresh(index: SkillIndex, nowMs: number): boolean {
  const t = Date.parse(index.generatedAt);
  if (Number.isNaN(t)) return false;
  return nowMs - t <= MAX_INDEX_AGE_MS;
}

// ── G-M4b: runtime-copy precedence ───────────────────────────────────────────

/** Where the background auto-refresh writes its copy (`~/.claude/prompt-coach/`). The
 *  COMMITTED data/skill-index.json is never touched at runtime. */
export function runtimeIndexPath(baseDir: string): string {
  return join(baseDir, 'skill-index.json');
}

/** A loaded index plus WHICH copy it came from (for the `/coach status` label). */
export interface LoadedSkillIndex {
  readonly index: SkillIndex;
  readonly source: 'runtime' | 'committed';
}

/**
 * D3 loader precedence: parse BOTH copies through the never-throw `loadSkillIndex`
 * validator; pick the runtime copy iff it is valid AND its generatedAt parses strictly
 * NEWER than the committed copy's. A corrupt/missing/older runtime copy → committed
 * fallback (never null while the committed copy is ok). Never throws.
 */
export function loadSkillIndexWithProvenance(
  baseDir: string,
  readCommitted: () => string = defaultRead,
): LoadedSkillIndex | null {
  const committed = loadSkillIndex(readCommitted);
  const runtime = loadSkillIndex(() => readFileSync(runtimeIndexPath(baseDir), 'utf8'));
  if (runtime === null) {
    return committed !== null ? { index: committed, source: 'committed' } : null;
  }
  if (committed === null) return { index: runtime, source: 'runtime' };
  const rt = Date.parse(runtime.generatedAt);
  const ct = Date.parse(committed.generatedAt);
  if (!Number.isNaN(rt) && !Number.isNaN(ct) && rt > ct) {
    return { index: runtime, source: 'runtime' };
  }
  return { index: committed, source: 'committed' };
}

/** The plain-index convenience wrapper over `loadSkillIndexWithProvenance`. */
export function loadSkillIndexPreferRuntime(
  baseDir: string,
  readCommitted: () => string = defaultRead,
): SkillIndex | null {
  return loadSkillIndexWithProvenance(baseDir, readCommitted)?.index ?? null;
}
